server:
  port: 9300


spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        format_sql: true
        show-sql: true

    defer-datasource-initialization: true

logging:
  level:
    com.example: debug


jwt:
  header: Authorization
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK # fill in base64 [command: echo {plain_text} | base64]
  access-token-validity-in-seconds: 86400
